### ISSUE TITLE
update CC icon in WISE

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#104]
![cc-logo](https://f.cloud.github.com/assets/119416/137951/fc63bd2e-7181-11e2-974a-81614f494f69.png)

then let Ethan know

**Comment by breity** [comment]
All set: https://github.com/WISE-Community/WISE-Portal/commit/c94578f7b9e5ac2ee3c4958a0f89df1bf4a2405e.  I also updated production.
