### ISSUE TITLE
Improve password changed confirmation message

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#107]
Hi,

Your password has been changed for your account with username: username.

[please ignore this email if you did not request your password to be changed]

-Team at My Portal Name

**Comment by geoffreykwan** [comment]
Done
https://github.com/WISE-Community/WISE-Portal/commit/7e568262e0ccc1cbef9a7dfbaa25e04834e04d1f
