### ISSUE TITLE
Student Registration and Add Project: Auto-Fetch Period using Forbidden Javascript Magic

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#119]
Use Forbidden Javascript Magic to detect when a student completely types in access code in the student registration page and add a project page.

Then fetch and populate the period drop-down using standard javascript code.

**Comment by geoffreykwan** [comment]
Done
https://github.com/WISE-Community/WISE-Portal/commit/2405b0292ded710be7483c53bc18a5f14d8d6322
