### ISSUE TITLE
Statistics page doesn't load, throws js error

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#123]
It was working earlier this week. What happen?

Error in Chrome console:
Uncaught TypeError: Cannot read property 'length' of undefined statistics.html:544
parseVLEStatistics statistics.html:544
getVLEStatisticsCallback statistics.html:512
deferred.resolveWith jquery.js:862
done jquery.js:6591
callback jquery.js:7382

**Comment by geoffreykwan** [comment]
Fixed. The problem might have been somehow caused when the server ran out of disk space. There's an entry in the statistics table in the db that does not have all the fields we usually store. This caused a null pointer in the js. I've added null pointer checks to resolve this issue.
https://github.com/WISE-Community/WISE-Portal/commit/dc88448713f7115a62d8824028791f96cc2318f7
