### ISSUE TITLE
Contact WISE issue type show up as null in email

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#136]
When I fill out the contact wise form, the "issue type" in the email that is sent to listeners is null, regardless of what I choose in the issue type select drop down.
# Contact WISE General Request

Name: mr. h
Email: xyz@cooldude.com
Issue Type: null
Summary: testing feedback to wise issue type
Description: testing
User System: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.65 Safari/537.36

Here's the email that I received:
![screen shot 2013-09-18 at 11 37 51 am](https://f.cloud.github.com/assets/119416/1167613/795b04e0-2091-11e3-9c17-09871ffb65c5.png)

**Comment by geoffreykwan** [comment]
Fixed

https://github.com/WISE-Community/WISE-Portal/commit/e6e427ed0fe375251be42133b9eaa7157e5aa5c4
