### ISSUE TITLE
Admin->Find Runs By Teacher->View Work

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#22]
Log in as admin,
do find runs by teacher, type in teacher username
click on view work for any of the runs.

The gradingtool loads but you only see the top part of the it. The rest gets cut off.

Doug and researchers would find this useful- they are going through a bunch of teachers and their runs and seeing the completion level for each one. Right now they have to log in as each individual teacher.

**Comment by breity** [comment]
Yep, I just need to make this open in a grading dialog like the teacher tools.  Will do soon.

**Comment by breity** [comment]
Fixed: https://github.com/WISE-Community/WISE-Portal/commit/231a0daa6bfc91e11b78802ccaff7a8012db67af
