### ISSUE TITLE
Statistics not working after 4.5 latest update

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#25]
JS is throwing exception
Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by hirokiterashima** [comment]
looks like latest update is still not working.  Different error this time:

text is undefined
[Break On This Error] return text.replace(/Node/gi, "");
statistics.html (line 618)

**Comment by geoffreykwan** [comment]
Fixed

https://github.com/WISE-Community/WISE-VLE/commit/909aee182a6dc4af94d109fd178629c1b9bea28e
