### ISSUE TITLE
Change teacher password improvement

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#28]
Right now this is how change teacher password works:
1. You type in teacher username
2. WISE resets that user's password and sends the new password to the user's email
3. User gets new password in the email

or 
1. You type in email address
2. WISE finds first user with that email address, changes its password and sends the new password to the user's email
3. User gets new password in the email.

The problem here is that anyone can type anybody else's username or email address and have the password changed.

This is how it should work:
1. You type in teacher username or email address
2. WISE sends email to the user with a link to change the password (valid for X min)
3. User gets email, can click on it to go to a change password page, or ignore it

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/a5252fa77869027414e2b2a0771f28ff847d00f3
