### ISSUE TITLE
Create Run step 5/5: don't use curriculum base dir in jsp

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#31]
page 5 of 5 of create run wizard has the curriculum_base_dir/projectDir in jsp.

<form onsubmit="return createRun('1881','LD','Cellular Respiration: Reflection','Photosynthesis: Initial Ideas.project.json','/usr/local/tomcat/7.0.21/webapps/curriculum//1860')" class="center" method="post">
                        <input type="submit" value="Back" name="_target3">
                        <input type="submit" value="Cancel" name="_cancel">
                        <input type="submit" value="Done" name="_finish" id="submit_form">
                        <input type="hidden" value="" name="newProjectId" id="newProjectId">
                    </form>

Fix this so we don't show the curriculum_base_dir.  use project Id

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/b70bb3f8198229efdc7c191bd93baa699c07157e
