### ISSUE TITLE
Teacher is owner of a project but project doesn't show up in project library

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Portal--Deprecated--#39]
1. Log in as janicevinco1
2. Go to 'Browse WISE Projects'
3. Search for 876
4. It will say 'Showing 1 Projects (from 53 total)' but you won't see any projects

**Comment by breity** [comment]
Yes, I can reproduce this too.  Looks like it's a display/filter issue, as
the search shows there was a project found but doesn't show it.  I'll work
on a fix.

On Mon, Apr 23, 2012 at 11:50 AM, Geoffrey Kwan <
reply@reply.github.com

> wrote:
> 1. Log in as janicevinco1
> 2. Go to 'Browse WISE Projects'
> 3. Search for 876
> 4. It will say 'Showing 1 Projects (from 53 total)' but you won't see any
>    projects
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/WISE-Community/WISE-Portal/issues/39

## 

Jonathan Lim-Breitbart

**Comment by breity** [comment]
This should fix it: https://github.com/WISE-Community/WISE-Portal/commit/a8a5de6459b96d78d3e41426c57dd84b6f8865c7.

It was a bug in the library display where the project family (root project) was not correctly set for certain projects.
