### ISSUE TITLE
New Teacher feature: "Delete" a project

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#45]
New feature: A teacher can delete a project that they own.

Requirements/Specs:
- Only the owner of the project can "delete" the project.
- Deleted projects disappear from the owner and shared owner's libraries forever.
- Deleted projects are not physically deleted from the disk; files still exist in the curriculum_dir.
- Owner cannot "undelete" a project, so owner must be prompted to verify that they really want to delete the project.

Thoughts:
This should be a simple implementation- just adding (or making use of an existing) column in the projects table that denotes if the project is "deleted" or not and looking at that boolean variable.  Nothing should actually be deleted, from the curriculum_base_dir and from the database. The only thing that changes is the teachers' view.

**Comment by geoffreykwan** [comment]
Done. Still need to remove the deleted projects from the authoring tool open project list but I'll do that after Jon finishes updating that part of the authoring tool.

Projects can be undeleted by logging in as the owner and then making this request with the project id and revive=true.
http://localhost:8080/webapp/deleteproject.html?projectId=3382&revive=true

https://github.com/WISE-Community/WISE-VLE/commit/0549b41ca4575728e6d3e2012862f54a0c981f06

https://github.com/WISE-Community/WISE-Portal/commit/66bb733b0630a8f27685cfcd644c0c355dd1ead8
