### ISSUE TITLE
Premade Comments: accessible from teacher homepage->management dropdown

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#53]

**Comment by hirokiterashima** [comment]
this probably requires refactoring the premadecomments tool so it could be launched outside of the gradingtool context.

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/b0970ceedea1ba601e4916cfef9b9a16a5aa17d8
