### ISSUE TITLE
Premade Comments: label comments

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#54]
Let user add labels to comments. Then let them filter a list by labels.

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-VLE/commit/163761a45a98ebf378de0bf5f778c8b23e100149

https://github.com/WISE-Community/WISE-Portal/commit/8acffd381f9986b62eae0c72db484d3d95f1de14
