### ISSUE TITLE
Admin portal: user info popups no longer popup.

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#55]
Uncaught ReferenceError: popup640 is not defined                                                           /webapp/admin/lookupstudent.html:88
onclick                                                                                                                                 /webapp/admin/lookupstudent.html:88

Where did popup640 go? I don't see it there anymore.

**Comment by breity** [comment]
Sorry, I forgot these popups were still being used in the admin portal.  I put them back.  Should remove again once the admin pages are updated.
