### ISSUE TITLE
Premade comments: loading... msg when launching from homepage

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#66]
when premade comments is launched from the teacher HP, show some sort of loading message so that users don't get confused.

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/b87844edd40c32d38b3406a09c24a6ac22cb6b0f

https://github.com/WISE-Community/WISE-VLE/commit/58700fef1e204ab63a101ec6717cf9c317c794fe
