### ISSUE TITLE
Edit Run Settings XMPP

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#67]
1. Change "enable XMPP" to "enable real-time classroom"
2. When "enable real-time classroom" is enabled/disabled, the "Classroom Monitor" link for the run in the run list should appear/disappear.

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/d07721498ebc3e45e8d6ad75ed1748d6c9183b59
