### ISSUE TITLE
Remove MaxWorkgroup = 3 assumption

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#71]
Allow each portal instance to specify maximum workgroup size in portal.properties

**Comment by hirokiterashima** [comment]
done:
https://github.com/WISE-Community/WISE-Portal/commit/db5ce3f33bb2fea2b0f424a84f01bf907dbc1f8b

**Comment by cbradyatinquire** [comment]
thanks,hiroki!! -c
