### ISSUE TITLE
remove remote YUI dependency from student Add A Project dialog

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#72]
replace with local jQuery so students don't need to make a request to apis.yahoo.com

**Comment by hirokiterashima** [comment]
done, committed
https://github.com/WISE-Community/WISE-Portal/commit/d027bd04ee93c28c7002fbfa3d86a5a45db2c4fb
https://github.com/WISE-Community/WISE-Portal/commit/4ecfa08b0c28c4fea98109effefcafd87df33354

**Comment by breity** [comment]
cool, thanks

On Wed, Oct 10, 2012 at 3:44 PM, Hiroki Terashima
notifications@github.comwrote:

> done, committed
> WISE-Community/WISE-Portal@d027bd0https://github.com/WISE-Community/WISE-Portal/commit/d027bd04ee93c28c7002fbfa3d86a5a45db2c4fb
> WISE-Community/WISE-Portal@4ecfa08https://github.com/WISE-Community/WISE-Portal/commit/4ecfa08b0c28c4fea98109effefcafd87df33354
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WISE-Community/WISE-Portal/issues/72#issuecomment-9322502.

## 

Jonathan Lim-Breitbart
