### ISSUE TITLE
Lookup runs/teachers that a student is associated with

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#76]
When a student fills out a trouble ticket, we have to:
1. find student
2. log in as student
3. find run(s)
4. find emails of teacher 

Make this into a tool in the admin panel.

**Comment by hirokiterashima** [comment]
assigned to geoff

**Comment by geoffreykwan** [comment]
Done

https://github.com/WISE-Community/WISE-Portal/commit/aecbf47847bd8e31b746818c8cc971828182a754
