### ISSUE TITLE
change teacherinfo.jsp to userinfo.jsp, move out of teacher dir

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#81]
right now it handles both teacher and student info so it should be renamed to userinfo.jsp and move it outside of the teacher directory

**Comment by geoffreykwan** [comment]
Done. Teacher now uses teacherinfo.jsp and student uses studentinfo.jsp.

https://github.com/WISE-Community/WISE-Portal/commit/8e1c2f07c434683ad2c3222476391431c64d6c8c
