### ISSUE TITLE
Contact WISE by student: contacts teacher

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#86]
Right now the student can fill out a contact WISE form, and it comes to us. We lookup the teacher for the student and contact the teacher.

I'm thinking that we can let the student choose from the teacher(s) that they are associated with when they fill out the form.

The student won't have an email address so there won't be a back-and-forth exchange with the teacher. All it does it send an email to the teacher (cc'ing us also) saying that the student needs help.  The email would look something like this:

Dear Mr. Geoff,

Your student, Hiroki Awesome, has filled out a WISE trouble ticket:

Project Name: Cellular Respiration 2011
Project ID: 5605
Issue Type: Need Help Using WISE
Summary: Project not opening
Description: When I try to open the respiration lab even on google chrome it does not open.  It opened a few days ago but now when I open it, the document remains white.
User System: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; HPNTDF; BRI/1; ibrytetoolbar_playbryte; .NET4.0C; BRI/2)

We recommend that you follow up with your student next class. If you need further assistance, you can write to wise4_email_here

WISE Staff

**Comment by geoffreykwan** [comment]
Done
https://github.com/WISE-Community/WISE-Portal/commit/6595f0caa61dfdf110315bf357fa3ef6eca01f2e
https://github.com/WISE-Community/WISE-Portal/commit/618dcefab88b506e00f284dbfce4e91f58db271f
