### ISSUE TITLE
Email text when setting up a run has a lot of null values

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Portal--Deprecated--#94]
The email that is sent when setting up a run looks like this

null

null: WISE4 Prod Portal
null: Geoffrey Kwan
null: GeoffreyKwan
null: ruddiger26@hotmail.com
null: Bikini Bottom High
null: Bikini Bottom, Sea
null: [1, 2]
null: [Viper878-1, Viper878-2]
null: Chemical Reactions: How Can We Slow Climate Change? MARTINEZ-A
null: 5950
null: 3471
null: Thu, January 17, 2013

null

**Comment by hirokiterashima** [comment]
fixed, committed. refactored some code along the way.
https://github.com/WISE-Community/WISE-Portal/commit/9d4a55e91aa6547ba3bf88dd75750307907291f2
