### ISSUE TITLE
Excellent Choice when creating possible duplicate account

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#95]
Explain what "Cancel" and "OK" does in this case.

![skitch](https://f.cloud.github.com/assets/119416/79254/18706452-61a8-11e2-9c9f-c62204679a4f.png)

**Comment by geoffreykwan** [comment]
Done mate.

https://github.com/WISE-Community/WISE-Portal/commit/85a42201b95a322db5295ce8637b8076a9e49f2e
